### ISSUE TITLE
Widget Parameter - Service Url  - General Usage for Drillisch Brands

### ISSUE THREAD

**Issue by markus82** [BergenSoft/scriptable_premiumsim#1]
Hi,
the script works very well also for other Drillisch brands like e. g. winsim, sim.de by changing the url to service.winsim.de, service.sim.de. 

Therefore my enhancement request to configure the url as Widget Parameter. 

Kind Regards
Markus

**Comment by BergenSoft** [comment]
Done, please check newest version. (98bfa98cbb414421057fa651b89d654b0e7d8c65)

**Comment by markus82** [comment]
Great. Works fine for sim.de also.
