### ISSUE TITLE
Cache Problem

### ISSUE THREAD

**Issue by Adrian-the-Analytics-Engineer** [BergenSoft/scriptable_premiumsim#3]
Hi, ich habe eine Fehlermeldung erhalten, dass es ein Cache Problem. Gibt. Es wird zu einem Ordner verlinkt den es nicht gibt.

**Comment by BergenSoft** [comment]
Kannst du die Ausgabe der Konsole mal hier einfügen?
Natürlich ohne Zugangsdaten, falls diese ausgegeben werden.

Aktuell funktioniert das Widget ehh nicht, da Drillisch ihre Webseiten umgestellt hat.
Und irgendwie funktioniert das laden der neuen Webseite mit Scriptable nicht so richtig.
Schaue mir das gerade an. Nicht dass dein Problem damit zusammen hängt.

**Comment by BergenSoft** [comment]
Das Laden der neuen Seite funktioniert jetzt.
Mache mal ein Update und gib Rückmeldung, ob dein Problem weiterhin besteht.

**Comment by Adrian-the-Analytics-Engineer** [comment]
2021-07-12 23:18:00: Cache Path: /private/var/mobile/Library/Mobile Documents/iCloud~dk~simonbs~Scriptable/Documents/PremiumSim/cache.json
2021-07-12 23:18:00: Error: Cannot download the file from iCloud because the file does not exist.

**Comment by Adrian-the-Analytics-Engineer** [comment]
Hier die Fehlermeldung. Es liegt wohl nicht an der HP.

**Comment by BergenSoft** [comment]
Das Problem könnte jetzt behoben sein. Mach mal bitte ein Update.
Ich habe auch ein weiteres Feature eingebaut um die Zugangsdaten direkt über das Script eingeben zu können, sofern noch keine gefunden wurden.

**Comment by Adrian-the-Analytics-Engineer** [comment]
@BergenSoft Klasse es klappt. :)
Danke, für die Mühe.
