### ISSUE TITLE
WinSIM

### ISSUE THREAD

**Issue by GalileoXXL** [BergenSoft/scriptable_premiumsim#4]
Hallo.
Ich habe Scriptable für WinSIM ausprobiert.
Ein mal ist das Script gestartet und hat nach Provider und LogIn gefragt. Dann kam Graphik und als ist eine Verknüpfung auf dem iPhone Bildschirm machen wolte ist es abgestürzt. Seit dem startet es nicht mehr und bringt Fehlermeldung: Error in line TypeError: null is not an object ( evaluating `m_Data.percent`)
Habe schon mehrmals alles gelöscht und Script neu heruntergeladen.. geht nicht.

Das andere Problem ist: ich habe 3 SIM Karten ( also auch 3x Vertrag mit 3 unterschiedlichen Telefonnummern. Alles läuft aber über ein LogIn in der WinSIM-Homepage. Irgendwie müsste noch ein Auswahlfenster in den Script um die richtige Handynummer auswählen zu müssen.

Danke für deine Mühe.

Gruss Edmund

**Comment by BergenSoft** [comment]
Sorry für die etwas verspätete Antwort.
Die eingegebenen Daten werden in einer separaten Datei gespeichert. Du findest diese in der "Dateien" App auf deinem iOS Gerät. Es scheint so, als ob das Skript die Werte nicht findet und daher das m_Data Objekt nicht gefüllt ist. Vermutlich hängt das zweite Problem damit zusammen. Da ich allerdings nur eine Nummer habe, kann ich es bei mir nicht testen und auch entsprechend nicht beheben.
