### ISSUE TITLE
keine Farbe im Ring

### ISSUE THREAD

**Issue by ghost** [BergenSoft/scriptable_premiumsim#5]
![Foto 01 10 23, 09 57 50](https://github.com/BergenSoft/scriptable_premiumsim/assets/146622254/9c09ff55-2e6d-490b-9a2d-1000cc0d130c)
Hallo,

ich habe seit längerem das Problem (trotz Update auf die neuste Version) das mir mein Datenvolumen von sim.de nicht mehr in Farbe angezeigt wird sondern nur als weißer Ring. Gibt es da Probleme ?

**Comment by BergenSoft** [comment]
Hallo,
Ein paar bekannte nutzen ebenfalls sim.de
Das sollte daher alles funktionieren. Daher vermute ich, dass die Zugangsdaten möglicherweise nicht mehr korrekt sind. 
Diese findest du im der Dateien App unter iCloud Drive -> Scriptable -> PremiumSim -> config.json
Die Datei kann auch einfach gelöscht werden, dann wird man beim nächsten Ausführen wieder nach den Zugangsdaten gefragt.

**Comment by ghost** [comment]
Hallo, ich habe die config.json gelöscht. Die Abfrage der Zugangsdaten kam und ich bin eingeloggt. Jedoch besteht das Problem weiterhin.....

**Comment by BergenSoft** [comment]
Möglicherweise kommt nach mehrfachem fehlgeschlagenem einloggen auch ein Captcha Code. Ist mir beim letzten Update vorbereiten aufgefallen.

**Comment by ghost** [comment]
also am iPhone bekomme ich keine Captcha Abfrage. Jedoch am PC im Browser wenn ich mich versuche in die Servicewelt einzuloggen: "Zu viele Anmelde-Fehlversuche." Nun ist die Frage wie ich das Problem am iPhone lösen kann. Es betrifft auch nur die Farbe und die Anzeige des Datenvolumes. Der weiße Ring selbst dreht sich immer weiter. die Anzeige jedoch bleibt alles auf 0

/EDIT ich habe nun über die Servicewelt mal das Login Passwort geändert und siehe da am iPhone zeigt er mir jetzt zumindest schonmal an wieviel GB ich insgesamt zur Verfügung habe.

**Comment by BergenSoft** [comment]
Der weiße Ring zeigt nur den Fortschritt des Monats an. Das geht unabhängig von Drillisch Login.
