### ISSUE TITLE
Widget wiedergibt Datenvolumen nicht

### ISSUE THREAD

**Issue by TheEviidence** [BergenSoft/scriptable_premiumsim#6]
Seit iOS 17.4 wird das Datenvolumen nicht mehr angezeigt. Ich bin beim Drillisch Provider "handyvertrag.de".
Davor hat alles problemlos funktioniert. Habe auch schon den Cache gelöscht. Dies hat leider auch nicht zum Erfolg geführt...

Das Widget sieht so aus:
![image](https://github.com/BergenSoft/scriptable_premiumsim/assets/140912777/441b831f-3166-43f0-b613-503ae252bb5d)

**Comment by BergenSoft** [comment]
Das Problem hab ich schon behoben, bitte auf die neuste Version Updaten. Drillisch hat ihr Seite umgebaut, daher wurden die Werte nicht mehr gefunden.

**Comment by TheEviidence** [comment]
Super! Danke dir viel Mals für die tolle Arbeit. Der Update Button ist komischerweise erst jetzt bei mir aufgetaucht.

Ich wünsche dir noch ein schönes Restwochenende :)

_ _ _ _ _
Mit freundlichen Grüßen
Yasin
________________________________
Von: BergenSoft ***@***.***>
Gesendet: Saturday, March 16, 2024 8:59:23 PM
An: BergenSoft/scriptable_premiumsim ***@***.***>
Cc: TheEviidence ***@***.***>; Author ***@***.***>
Betreff: Re: [BergenSoft/scriptable_premiumsim] Widget wiedergibt Datenvolumen nicht (Issue #6)


Closed #6<https://github.com/BergenSoft/scriptable_premiumsim/issues/6> as completed.
